force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Max_Pay__c.field-meta.xml
<CustomField>
    <fullName>Max_Pay__c</fullName>
    <label>Max Pay</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Min_Pay__c.field-meta.xml
<CustomField>
    <fullName>Min_Pay__c</fullName>
    <label>Min Pay</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Date__c</fullName>
    <label>Open Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PositionTriggerHandler.cls
public with sharing class PositionTriggerHandler {
    
    public static void autoFill(List<Position__c> posList){
        for(Position__c pos:posList){
            if(pos.Open_Date__c == null){
                pos.Open_Date__c= Date.today();
            }
            if(pos.Min_Pay__c == null){
                pos.Min_Pay__c=10000;
            }
            if(pos.Max_Pay__c == null){
                pos.Max_Pay__c=15000;
            }
        }
    }
}